---

- name: Install haproxy
  apt:
    default_release:    "{{ debian_release }}-backports"
    name:               haproxy
    state:              latest

- name: Install haproxy config
  template:
    src:        etc/haproxy/haproxy.cfg
    dest:       /etc/haproxy/haproxy.cfg
    mode:       '0640'
    owner:      root
    group:      haproxy
    validate:   "/usr/sbin/haproxy -c -f %s"
  notify: restart haproxy

- name: Overwrite haproxy rsyslog config
  template:
    src:        "etc/rsyslog.d/haproxy.conf"
    dest:       "/etc/rsyslog.d/haproxy.conf"
    mode:       "0640"
    owner:      root
    group:      root
  notify: restart rsyslog

- name: Enable haproxy system daemon
  service:
    name:       haproxy
    state:      started
    enabled:    yes
